# Generated by Django 3.0.7 on 2021-02-01 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Картинка', max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('location', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='places.Location')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
