# Generated by Django 3.0.7 on 2021-02-04 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_location_details_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position']},
        ),
    ]
