# Generated by Django 3.0.7 on 2021-03-18 11:44

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20210205_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='coordinates_lat',
            new_name='lat_coordinate',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='coordinates_lng',
            new_name='lng_coordinate',
        ),
        migrations.RemoveField(
            model_name='location',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='location',
            name='short_description',
        ),
        migrations.AddField(
            model_name='location',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, default='Подробное описание'),
        ),
        migrations.AddField(
            model_name='location',
            name='short_description',
            field=models.TextField(blank=True, default='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, default='Картинка', max_length=100),
        ),
    ]
