# Generated by Django 3.0.7 on 2021-03-18 13:06

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20210318_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='preview',
            field=models.TextField(blank=True, verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='файл картинки'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat_coordinate',
            field=models.FloatField(verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng_coordinate',
            field=models.FloatField(verbose_name='долгота'),
        ),
        migrations.AlterField(
            model_name='location',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='location',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Заголовок'),
        ),
    ]
